// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3QD1UW3PgjFxFDMmbdWhLAKA8sIQ94VA',
    appId: '1:295050447190:web:4ad84a924390298d50eef7',
    messagingSenderId: '295050447190',
    projectId: 'newapp-2580d',
    authDomain: 'newapp-2580d.firebaseapp.com',
    storageBucket: 'newapp-2580d.appspot.com',
    measurementId: 'G-QL8VX6RP5J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDkfCdpv_V4-mDfMkLylw7B-7GKs1ZJApQ',
    appId: '1:295050447190:android:3ca5635536ed8ca750eef7',
    messagingSenderId: '295050447190',
    projectId: 'newapp-2580d',
    storageBucket: 'newapp-2580d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmbGShwmU1lVg6wBgaSV-2ajKaRNYXMpY',
    appId: '1:295050447190:ios:cbf8b965ade07e8c50eef7',
    messagingSenderId: '295050447190',
    projectId: 'newapp-2580d',
    storageBucket: 'newapp-2580d.appspot.com',
    iosBundleId: 'com.example.ase',
  );
}
